sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - clang
  - gcc
script: "./.travis/build"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-system-dev libboost-thread-dev libboost-test-dev libtinyxml-dev python-yaml python-mock
matrix:
  allow_failures:
    - compiler: clang
